addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: 45c58dcf-971b-4693-ac3a-9492b8c81b6b
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 720 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install: []
branches: ''
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.m2
install: /bin/true
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=45c58dcf-971b-4693-ac3a-9492b8c81b6b
script:
- mvn install -Dskip.unit.tests=true -Dmaven.javadoc.skip=true -V -B
- mvn test coveralls:report -V -P coverage
sudo: false
# Modified by Insights Service at 2016-11-27 18:26:10.376172
